# https://docs.astral.sh/ruff/settings/#lintisort
[tool.ruff.lint.isort]
force-wrap-aliases = true  # Записывать импорты с несколькими `as` в кортеже
combine-as-imports = true  # Записывать импорты с несколькими `as` в одной строке
# force-sort-within-sections = true  # Всегда сортировать импорты по алфавиту, не обращая внимание на порядок import или from
# from-first = true  # Записывать from импорты перед import
# length-sort = true  # Сортировать импорты по длине строки а не по алфавиту
lines-after-imports = 2  # Количество пустых строк после последнего импорта
# order-by-type = true  # Сортировать по регистру в дополнение к сортировке по алфавиту
# required-imports = ["from __future__ import annotations"]  # Добавить импорт во все файлы


# https://docs.astral.sh/ruff/settings/
# https://docs.astral.sh/ruff/configuration/#full-command-line-interface
# cmd: ruff format  # Отформатирует все файлы в `.` текущем каталоге.
[tool.ruff]
# required-version = "==0.3.1"
target-version = "py311"  # Минимальная версия python которую будет обслуживать ruff
line-length = 120  # Макс длина строки кода после которой будет выполнен автоперенос
indent-width = 4
force-exclude = true  # pre-commit файл будет использовать exclude список
src = ["."]  # Корень проекта в котором лежат приложения  (необходимо для работы ruff.lint.isort)
extend-exclude = [
    "migrations",
]


[tool.ruff.format]
quote-style = "double"  # Использовать двойные кавычки при форматировании файла
indent-style = "space"  # Использовать пробелы вместо табуляции при форматировании файла
line-ending = "lf"  # Последовательность конца строки для файлов по умолчанию


[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"  # Не ругаться на двойные кавычки
docstring-quotes = "double"  # Ругаться на двойные кавычки


# https://docs.astral.sh/ruff/linter/
# cmd: ruff check --fix  # Проверить линтером все файлы в `.` текущем каталоге и исправить все безопасные проблемы.
[tool.ruff.lint]
# typing-modules = [""]  # Объекты из этого модуля будут расцениваться как типы
# Настройки по умолчанию: https://docs.astral.sh/ruff/configuration/
# https://docs.astral.sh/ruff/rules/
# select по умолчанию: ["E4", "E7", "E9", "F"]
extend-select = [
    # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    # https://docs.astral.sh/ruff/rules/#isort-i
    "I",  # isort
    # https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "N",  # pep8-naming
    # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "UP",  # pyupgrade
    # https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
    "YTT",  # flake8-2020
    # https://docs.astral.sh/ruff/rules/#flake8-async-async
    "ASYNC",  # flake8-async
    # https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble
    "BLE",  # flake8-blind-except
    # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "B",  # flake8-bugbear
    # https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "A",  # flake8-builtins
    # https://docs.astral.sh/ruff/rules/#flake8-commas-com
    "COM",  # flake8-commas
    # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "C4",  # flake8-comprehensions
    # https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
    "DTZ",  # flake8-datetimez
    # https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
    "T10",  # flake8-debugger
    # https://docs.astral.sh/ruff/rules/#flake8-django-dj
    "DJ",  # flake8-django
    # https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
    "FA",  # flake8-future-annotations
    # https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc
    "ISC",  # flake8-implicit-str-concat
    # https://docs.astral.sh/ruff/rules/#flake8-import-conventions-icn
    "ICN",  # flake8-import-conventions
    # https://docs.astral.sh/ruff/rules/#flake8-logging-format-g
    "G",  # flake8-logging-format
    # https://docs.astral.sh/ruff/rules/#flake8-no-pep420-inp
    "INP",  # flake8-no-pep420
    # https://docs.astral.sh/ruff/rules/#flake8-pie-pie
    "PIE",  # flake8-pie
    # https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi
    "PYI",  # flake8-pyi
    #! https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
    #! "PT",  # flake8-pytest-style  (мешает юниттестам)
    # https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    "Q",  # flake8-quotes
    # https://docs.astral.sh/ruff/rules/#flake8-raise-rse
    "RSE",  # flake8-raise
    # https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "RET",  # flake8-return
    # https://docs.astral.sh/ruff/rules/#flake8-self-slf
    "SLF",  # flake8-self
    # https://docs.astral.sh/ruff/rules/#flake8-slots-slot
    "SLOT",  # flake8-slots
    # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "SIM",  # flake8-simplify
    # https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid
    "TID",  # flake8-tidy-imports
    # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
    "TCH",  # flake8-type-checking
    # https://docs.astral.sh/ruff/rules/#flake8-gettext-int
    "INT",  # flake8-gettext
    #! https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
    #! "ARG",  # flake8-unused-arguments  (спорно)
    # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "PTH",  # flake8-use-pathlib
    #! https://docs.astral.sh/ruff/rules/#eradicate-era
    #! "ERA",  # eradicate  (спорно)
    # https://docs.astral.sh/ruff/rules/#flynt-fly
    "FLY",  # flynt
    # https://docs.astral.sh/ruff/rules/#perflint-perf
    "PERF",  # Perflint
    #! https://docs.astral.sh/ruff/rules/#refurb-furb
    #! "FURB",  # refurb  (пока что не стабильно 29.03.2024)
    # https://docs.astral.sh/ruff/rules/#flake8-logging-log
    "LOG",  # flake8-logging
    # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "RUF",  # Ruff-specific rules
]
ignore = [
    # https://docs.astral.sh/ruff/rules/#pyflakes-f
    "F401",  # unused-import
    "F841",  # unused-variable
    # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "UP031",  # printf-string-formatting  (не ругаться на форматирование с помощью %s)
    # https://docs.astral.sh/ruff/rules/#flake8-logging-format-g
    "G004",  # logging-f-string  (не ругаться на использование f-строк для сообщения лога)
    # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "RUF001",  # ambiguous-unicode-character-string  (не ругаться на кириллицу в строках)
    "RUF002",  # ambiguous-unicode-character-docstring  (не ругаться на кириллицу в докстрингах)
    "RUF003",  # ambiguous-unicode-character-comment  (не ругаться на кириллицу в комментариях)
    "RUF012",  # mutable-class-default  (не ругаться на мутабельность коллекций)
    # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
    "PT009",  # pytest-unittest-assertion  (не ругаться на unittest ассерты)
    # https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc
    "ISC001",  # single-line-implicit-string-concatenation  (конфликт с `COM812`)
    # https://docs.astral.sh/ruff/rules/#flake8-commas-com
    "COM812", # flake8-commas  (конфликт с `ISC001`)
    "UP005", # assert вместо self.assertEquals
]
# Не давать исправлять эти ошибки в тултипе, и в том числе автоматически при линте через команду
unfixable = [
]


[tool.ruff.lint.flake8-self]
# https://docs.astral.sh/ruff/rules/#flake8-self-slf
# (не ругаться на приватные названия объектов)
extend-ignore-names = ["_base_manager", "_default_manager", "_meta"]  # Перекрывает "SLF001" (private-member-access)


[tool.ruff.lint.flake8-comprehensions]
# https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
# {} VS dict()  # https://switowski.com/blog/dict-function-vs-literal-syntax/
# (не ругаться на использование классов коллекций вместо их литералов)
allow-dict-calls-with-keyword-arguments = true  # Перекрывает "C408" (unnecessary-collection-call)


[tool.ruff.lint.flake8-bugbear]
# Не ругаться на установку указанных объектов в качестве значений по умолчанию у аргументов функций
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.Query"
]


[tool.ruff.lint.pycodestyle]
max-line-length = 120  # Макс длина строки кода после которой будет отображено предупреждение
max-doc-length = 120  # Макс длина строки документации после которой будет отображено предупреждение

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \venv
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 120
py_version=311
skip = [".gitignore", ".dockerignore", 'venv', 'migrations']
balanced_wrapping=true
lines_after_imports=2

[tool.pyright]
pythonVersion = "3.11"
pythonPlatform = "Linux"
reportGeneralTypeIssues = false
